<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Tmds.DBus" Version="0.94.1" />
        <ProjectReference Include="..\Tp358.Ble.Abstractions\Tp358.Ble.Abstractions.csproj" />
    </ItemGroup>

</Project>
